name: Autotest

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3
    steps:
      - uses: actions/checkout@v3
        with:
          python-version: 3
      - run: npm ci
      - run: npm test
      - run: npm run build
