name: Autotest

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3
    steps:
      - uses: actions/checkout@v3
      - run: pip install pytest
      - run: python3 main.py
      - run: pytest main.py
